-- Create the quote table (PostgreSQL compatibility mode)
CREATE TABLE quote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id VARCHAR(50),
    basic_quote_id VARCHAR(50),
    customer_name VARCHAR(100),
    customer_email VARCHAR(100),
    customer_phone VARCHAR(20),
    request_text VARCHAR(255),
    created_time TIMESTAMP,
    opt_in BOOLEAN
);
